sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBrc4sSjsuEnKk5vVGr
    access-key-secret: 7ssDexvYbQViLsjcKvRS9Ibd2jRQDu
    bucket-name: theodore19991107
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxd6787dce2d1fb7e7
    secret: 2676a7a6dd5168b8f66df65236a2a461


